package it.unina.Boundary;

import java.lang.String;
import javax.swing.JOptionPane;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import it.unina.Controller.CGestioneAccount;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;

public class FormAutenticazione {
    private JPanel jpPrincipale;
    private JTextField tfEmail;
    private JPanel jpTitolo;
    private JPanel jpEmail;
    private JPanel jpPassword;
    private JButton accediButton;
    private JPasswordField passwordField1;
    private JLabel jleffettivo;
    private JLabel jlesitoop;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        jpPrincipale = new JPanel();
        jpPrincipale.setLayout(new GridLayoutManager(6, 7, new Insets(0, 0, 0, 0), -1, -1));
        jpPrincipale.setPreferredSize(new Dimension(450, 350));
        jpTitolo = new JPanel();
        jpTitolo.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        jpPrincipale.add(jpTitolo, new GridConstraints(0, 0, 1, 7, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jpTitolo.setBorder(BorderFactory.createTitledBorder(null, "Form AUTENTICAZIONE", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        jpEmail = new JPanel();
        jpEmail.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        jpPrincipale.add(jpEmail, new GridConstraints(1, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jpEmail.setBorder(BorderFactory.createTitledBorder(null, "inserire l'email:", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        jpPassword = new JPanel();
        jpPassword.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        jpPrincipale.add(jpPassword, new GridConstraints(3, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        jpPassword.setBorder(BorderFactory.createTitledBorder(null, "inserire la password:", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        tfEmail = new JTextField();
        jpPrincipale.add(tfEmail, new GridConstraints(1, 6, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final Spacer spacer1 = new Spacer();
        jpPrincipale.add(spacer1, new GridConstraints(2, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        jpPrincipale.add(spacer2, new GridConstraints(4, 0, 1, 6, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        passwordField1 = new JPasswordField();
        jpPrincipale.add(passwordField1, new GridConstraints(3, 6, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        accediButton = new JButton();
        accediButton.setText("Accedi");
        jpPrincipale.add(accediButton, new GridConstraints(4, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jleffettivo = new JLabel();
        jleffettivo.setText("attesa esito");
        jpPrincipale.add(jleffettivo, new GridConstraints(5, 6, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        jlesitoop = new JLabel();
        jlesitoop.setText("esito operazione");
        jpPrincipale.add(jlesitoop, new GridConstraints(5, 0, 1, 6, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return jpPrincipale;
    }

    public FormAutenticazione() {
        accediButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                onClickAccedi();
            }
        });
    }

    private void onClickAccedi() {
        String email = tfEmail.getText();
        char[] password = passwordField1.getPassword();

        try {
            // Mantiene il contratto della validazione attuale, mentre il controller riceve la password come char array.
            if (!verificaFormatoDati(email, String.valueOf(password))) {
                return;
            }

            // Delega al controller il controllo delle credenziali, lasciando alla form solo la gestione dell'interfaccia.
            CGestioneAccount gestioneAccount = new CGestioneAccount();
            boolean esito = gestioneAccount.gestisciAutenticazione(email, password);

            if (esito) {
                jleffettivo.setText("Accesso eseguito.");
                jleffettivo.setForeground(Color.GREEN);
            } else {
                // Non distingue e-mail e password errate per non rivelare quali account sono registrati.
                jleffettivo.setText("Credenziali non valide.");
                jleffettivo.setForeground(Color.RED);
            }
        } finally {
            // Cancella la password dalla memoria appena termina il tentativo di accesso.
            Arrays.fill(password, '\0');
        }
    }

    public boolean verificaFormatoDati(String email, String password) {
        if (email == null || email.isBlank() || password == null || password.length() == 0) {
            JOptionPane.showMessageDialog(
                    jleffettivo,
                    "Inserisci e-mail e password.",
                    "Dati mancanti",
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        // Richiede la chiocciola per evitare di inviare al controller un'e-mail palesemente incompleta.
        if (email.indexOf('@') != 1) {
            JOptionPane.showMessageDialog(
                    jleffettivo,
                    "L'e-mail deve contenere il carattere @.",
                    "E-mail non valida",
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        // Impedisce l'accesso con una password fuori dai limiti previsti per l'autenticazione.
        if (password.length() < 8 || password.length() > 15) {
            JOptionPane.showMessageDialog(
                    jleffettivo,
                    "La password deve contenere da 8 a 15 caratteri.",
                    "Password non valida",
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        // Richiede almeno un carattere speciale per rispettare la regola di robustezza della password.
        if (!contieneCarattereSpeciale(password)) {
            JOptionPane.showMessageDialog(
                    jleffettivo,
                    "La password deve contenere almeno un carattere speciale.",
                    "Password non valida",
                    JOptionPane.WARNING_MESSAGE
            );
            return false;
        }

        return true;
    }



    // Cerca caratteri speciali ammessi senza convertire la password in una String persistente in memoria.
    private boolean contieneCarattereSpeciale(String password) {
        String caratteriSpeciali = "!@#$%^&*()_+-=[]{};:'\",.<>/?\\|";

        for (String carattere : password) {
            if (caratteriSpeciali.indexOf(carattere) >= 0) {
                return true;
            }
        }

        return false;
    }


}
